CONFIG_SETTINGS=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_NP0_G0=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_I2C=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
